runtime: nodejs20
env: standard
instance_class: F1
entrypoint: npm run start:api

automatic_scaling:
  max_instances: 1
  min_instances: 0






# runtime: nodejs20
# env: standard
# instance_class: F2
# entrypoint: npm run start:api
# automatic_scaling:
#   min_instances: 1   # keeps 1 instance alive
#   max_instances: 1
